# service, headless service, statefulset, pvc
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    component: mongodb
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: db
  serviceName: "mongodb-headless" # this should be head less service name
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: db # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: eshwarkodavali/mongodb:v1
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
    # This is PVC
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi